function bigbrain2fsaverage(lhData, rhData, outName, bbwDir)
% nearest neighbour interpolation between bigbrain and fsaverage5
% indexing was pre-generated by Casey, you can find the creation script in "nn_surface_indexing.m" 
%
% input:
% lhData              data on the left hemisphere (1 x 163842)
% rhData              data on the right hemisphere (1 x 163842)
% outName             name of output file (will be apended with "_fsaverage5")
% bbwDir              /path/to/BigBrainWarp/
% 
% Compatible data input types include:
% .annot               requires Freesurfer matlab component
% .gifti               requires gifti toolbox (https://www.artefact.tk/software/matlab/gifti/)
% .thickness           requires Freesurfer matlab component
% .curv                requires Freesurfer matlab component 
% .mgh                 requires Freesurfer matlab component 
% .txt
% 
% the default output is a single .txt file, however, the output will be 
% hemisphere-specific .curv or .mgh if these are input. We can expand the 
% the compatibility as demand requires
% 
% author: Casey Paquola @ MICA, MNI, 2020*

% convert variables to character vectors
outName = char(outName);
bbwDir = char(bbwDir);
addpath([bbwDir '/scripts'])

% load and vectorise surface data
[~,~,ext] = fileparts(lhData);
if strcmp(ext, '.annot')
    parc = annot2classes(lhData, rhData, 0);
    lh_input = parc(1:end/2)';
    rh_input = parc((end/2)+1:end)';
elseif strcmp(ext, '.gii')
    tmp = gifti(lhData);
    lh_input = tmp.cdata';
    tmp = gifti(rhData);
    rh_input = tmp.cdata';
elseif strcmp(ext, '.curv')
    lh_input = read_curv(lhData)';
    rh_input = read_curv(rhData)';
elseif strcmp(ext, '.mgh')
    lh_input = load_mgh(char(lhData));
    rh_input = load_mgh(char(rhData));
else
    lh_input = readmatrix(lhData);
    rh_input = readmatrix(rhData);
end

% check size and transpose if necessary
compatSizes = 163842;
if sum(size(lh_input)==size(rh_input))~=2
   error('hemispheric data not the same size');
end
if ~ismember(size(lh_input,2), compatSizes)
    if ismember(size(lh_input,1), compatSizes)
        lh_input = lh_input';
        rh_input = rh_input';
    else
        error('invalid number of vertices');
	disp(["lhData is " size(lh_input)])
	disp(["rhData is " size(rh_input)])
    end
end

% load indexing scheme
load([bbwDir '/scripts/nn_surface_indexing.mat'], 'nn_bb10_fs', 'bb_downsample');

% re-index to 10k BigBrain surface
data_bb = [lh_input rh_input];
data_bb10k = data_bb(bb_downsample);
data_fs = data_bb10k(nn_bb10_fs);

% write out
if strcmp(ext, '.curv')
    write_curv(data_fs(1:length(data_fs)/2), [outName '_lh_fsaverage5.curv'], 20480)
    write_curv(data_fs((length(data_fs)/2)+1:end), [outName '_rh_fsaverage5.curv'], 20480)
elseif strcmp(ext, '.mgh')
    M = [-0.001 0 0 5.121; 0 0 0.001 -0.0005; 0 -0.001 0 0.0005; 0 0 0 0.001]*1000; % taken from a curvature file on fsaverage5
    save_mgh(data_fs(1:length(data_fs)/2), [outName '_lh_fsaverage5.mgh'], M)
    save_mgh(data_fs((length(data_fs)/2)+1:end), [outName '_rh_fsaverage5.mgh'], M)
else
    writematrix(data_fs, [outName '_fsaverage5.txt'])
end
